### PR TITLE
0.2 8-char base32 identifiers

### PR DESCRIPTION
**Pull request by ckrey**
no PUB to ypom/+, out of band id/key exchange
signed and encyrpted

### CODE REVIEW

**Comment by jpmens** [comment]
I'm merging this now although I have no time to test now.
Not sure I like the disappearance of the clear username

**Comment by jpmens** [comment]
@ckrey and then I did test:

./create-ME.py
...
./ypom-cli
Cannot load `me.creds': Decryption failed. Ciphertext failed verification

**Comment by ckrey** [comment]
In IOS, identifiers can be linked to address book entries. So the IDENTIFIER becomes a NAME or even an IMAGE.

For CLI, we may prepend each address line in `users` by the NAME and work with it

**Comment by ckrey** [comment]
@jpmens sorry, please touch `users`

and, I had a problem (probably sitting in front of the screen) subscribe (ypom-cli.py line 186...)

```
$ ./create-ME.py 
Enter password to protect private key: 
Re-enter same password: 
id: 4OL3I65W
$ ./ypom-cli.py 
Enter password to decrypt private key: 
I am:>4OL3I65W<
Cannot load `me.creds': [Errno 2] No such file or directory: 'users'
$ ls
README.md   create-ME.py    me.creds    me.ypom     ypom-cli.py
$ touch users
$ ./ypom-cli.py 
Enter password to decrypt private key: 
I am:>4OL3I65W<
Use TAB-completion for identifier. (quit to exit)
4OL3I65W> subscribing to >ypom/4OL3I65W/+< 
OOOOPS! disconnect
$ 
```

**Comment by jpmens** [comment]
My fault: $YPOMCREDSPW was incorrect. Will test later.

**Comment by ckrey** [comment]
Take your time

@jpmens my fault, should have tested explicitly for `users` file exists

**Pull request merged**
